/**
 * @file  src/lib/errors/admin.ts
 * @owner Dev B
 * @module admin
 *
 * Admin domain error constants.
 *
 * Exports:
 *   - ADMIN_ERRORS
 */

export const ADMIN_ERRORS = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  AGENT_ALREADY_ACTIVE: "AGENT_ALREADY_ACTIVE",
  AGENT_ALREADY_REJECTED: "AGENT_ALREADY_REJECTED",
  REJECT_NOTE_REQUIRED: "REJECT_NOTE_REQUIRED",
  RETRY_NOT_ALLOWED: "RETRY_NOT_ALLOWED",
  IPFS_UPLOAD_FAILED: "IPFS_UPLOAD_FAILED",
  ERC8004_REGISTER_FAILED: "ERC8004_REGISTER_FAILED",
  PLATFORM_WALLET_INSUFFICIENT_BALANCE: "PLATFORM_WALLET_INSUFFICIENT_BALANCE",
  COLLECTION_POINTER_NOT_CONFIGURED: "COLLECTION_POINTER_NOT_CONFIGURED",
  RECEIPT_NOT_FOUND: "RECEIPT_NOT_FOUND",
  ALREADY_SUBMITTED: "ALREADY_SUBMITTED",
} as const;

export type AdminErrorCode = (typeof ADMIN_ERRORS)[keyof typeof ADMIN_ERRORS];
